[package]
name = "tracepulse"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"
sha1 = "0.10"
surge-ping = "0.8"
toml = "0.8"
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
rusqlite = { version = "0.32", features = ["bundled"] }
thiserror = "2.0"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
snmp = "0.2.2"
ratatui = "0.28"
crossterm = "0.28"
socket2 = "0.5"
windows-sys = { version = "0.59", features = [
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_System_IO",
] }
