name = "TP-LINK Smart / Managed Switch"
enterprise_id = 11863

[cpu]
candidates = [
    "1.3.6.1.4.1.11863.6.4.1.1.1.1.3", # TPLINK-SYSMONITOR-MIB::tpSysMonitorCpu1Minute
    "1.3.6.1.2.1.25.3.3.1.2",          # HOST-RESOURCES-MIB::hrProcessorLoad
]

[memory]
mode = "direct"
util_prefix = "1.3.6.1.4.1.11863.6.4.1.2.1.1.2" # TPLINK-SYSMONITOR-MIB::tpSysMonitorMemoryUtilization (%)